#!/usr/bin/bash
# Super-simple build script for C

if [ -z "$1"]; then
    echo -e "\033[1mUsage:\033[0m build filename.c"
    exit 1
fi

INPUT=$1
OUTPUT=$(echo "$INPUT" | sed 's/.c$//')

if [ ! -f "$INPUT" ]; then
    echo "File does not exist"
    exit
fi

gcc -Wall -Wextra -Wpedantic --std=c11 $INPUT -o $OUTPUT

