#!/usr/bin/bash
# Super-simple build script for C

if [ -z "$1" ]
then
    echo -e "\033[1mUsage:\033[0m build filename1.c filename2.c ..."
    echo "First filename becomes excutable name."
    exit 1
fi

for FILE in $@
do
    if [ ! -f "$FILE" ]
    then
        echo "File '$FILE' does not exist."
        exit
    fi
done

OUTPUT=$(echo "$1" | sed 's/.c$//')

gcc -Wall -Wextra -Wpedantic -Werror --std=c11 -g3 $@ -o $OUTPUT

