#!/usr/bin/env ruby

# Heads or Tails
class Coin
  def initialize
    @heads = 'Heads'
    @tails = 'Tails'
    @heads_count = 0
    @tails_count = 0
    @limit = 5
    @runs = 1
    @data = []
  end

  def to_s
    @data.join("\n")
  end

  # Flip the coin x times for y runs
  def flip
    (1..@runs).each do
      (1..@limit).each do
        if rand(0..1) == 1
          @heads_count += 1
        else
          @tails_count += 1
        end
      end

      update
    end
  end

  # setters for certain fields
  attr_writer :heads, :tails, :limit, :runs

  private

  def update
    @data.append("#{@heads}: #{@heads_count}, #{@tails}: #{@tails_count}")
    @heads_count = 0
    @tails_count = 0
  end
end

coin = Coin.new

# can supply coin names
if ARGV.size >= 2
  coin.heads = ARGV[0]
  coin.tails = ARGV[1]
end

# can supply number of flips
coin.limit = ARGV[2].to_i if ARGV.size >= 3

# can supply number of runs of flips
coin.runs = ARGV[3].to_i if ARGV.size >= 4

coin.flip
puts coin
